# Generated by Django 6.0.1 on 2026-01-23 10:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GovernanceDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('org_id', models.UUIDField(db_index=True)),
                ('title', models.CharField(max_length=255)),
                ('document_type', models.CharField(choices=[('RESOLUTION', 'Board Resolution'), ('MINUTES', 'Meeting Minutes'), ('BYLAW', 'Bylaws'), ('SOA', 'Statement of Account'), ('FIN_OP', 'Statement of Financial Operations'), ('FIN_POS', 'Statement of Financial Position'), ('CASH_FLOW', 'Statement of Cash Flows'), ('FUND_BALANCE', 'Statement of Changes in Fund Balance'), ('OTHER', 'Other')], default='RESOLUTION', max_length=20)),
                ('document_date', models.DateField()),
                ('file_url', models.URLField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('uploaded_by_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Governance Document',
                'verbose_name_plural': 'Governance Documents',
                'ordering': ['-document_date'],
            },
        ),
        migrations.CreateModel(
            name='DocumentRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('org_id', models.UUIDField(db_index=True)),
                ('document_type', models.CharField(choices=[('RESOLUTION', 'Board Resolution'), ('MINUTES', 'Meeting Minutes'), ('BYLAW', 'Bylaws'), ('SOA', 'Statement of Account'), ('FIN_OP', 'Statement of Financial Operations'), ('FIN_POS', 'Statement of Financial Position'), ('CASH_FLOW', 'Statement of Cash Flows'), ('FUND_BALANCE', 'Statement of Changes in Fund Balance'), ('OTHER', 'Other')], default='SOA', max_length=20)),
                ('purpose', models.TextField(help_text='Purpose of the request for transparency.')),
                ('date_range_start', models.DateField(blank=True, null=True)),
                ('date_range_end', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('GENERATED', 'Generated')], default='PENDING', max_length=20)),
                ('rejection_reason', models.TextField(blank=True)),
                ('generated_file', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_requests', to=settings.AUTH_USER_MODEL)),
                ('requestor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document Request',
                'verbose_name_plural': 'Document Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
