# Generated by Django 5.2.10 on 2026-01-27 09:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('org_id', models.UUIDField(db_index=True)),
                ('action', models.CharField(help_text='Action performed (e.g., DELETE_UNIT)', max_length=50)),
                ('target_type', models.CharField(help_text='Type of object acted on (e.g., Unit)', max_length=50)),
                ('target_id', models.UUIDField(help_text='ID of the object acted on')),
                ('target_label', models.CharField(blank=True, help_text='Human-readable label of the object', max_length=255)),
                ('performed_at', models.DateTimeField(auto_now_add=True)),
                ('context', models.JSONField(blank=True, default=dict, help_text='Additional context/metadata')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-performed_at'],
            },
        ),
    ]
