# Generated by Django 6.0.1 on 2026-01-12 09:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('org_id', models.UUIDField(db_index=True)),
                ('section_identifier', models.CharField(help_text='Block or Floor', max_length=50)),
                ('unit_identifier', models.CharField(help_text='Lot or Unit', max_length=50)),
                ('location_name', models.CharField(blank=True, help_text='Street or Building Name', max_length=100)),
                ('category', models.CharField(choices=[('UNIT', 'Unit'), ('INFRASTRUCTURE', 'Infrastructure')], default='UNIT', max_length=20)),
                ('owner_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('owner_name', models.CharField(blank=True, max_length=255)),
                ('owner_email', models.EmailField(blank=True, max_length=254)),
                ('owner_phone', models.CharField(blank=True, max_length=20)),
                ('resident_name', models.CharField(blank=True, help_text='Main point of contact', max_length=255)),
                ('membership_status', models.CharField(choices=[('GOOD_STANDING', 'Good Standing'), ('DELINQUENT', 'Delinquent'), ('NON_MEMBER', 'Non-Member')], default='GOOD_STANDING', max_length=20)),
                ('occupancy_status', models.CharField(choices=[('INHABITED', 'Inhabited'), ('VACANT', 'Vacant'), ('UNDER_CONSTRUCTION', 'Under Construction')], default='INHABITED', max_length=20)),
                ('dhsud_membership_date', models.DateField(blank=True, null=True)),
                ('voter_eligible', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['section_identifier', 'unit_identifier'],
                'unique_together': {('org_id', 'section_identifier', 'unit_identifier', 'location_name')},
            },
        ),
    ]
