# Generated by Django 6.0.1 on 2026-01-13 13:59

import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreditTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('unit_credit_id', models.UUIDField(db_index=True)),
                ('transaction_id', models.UUIDField(blank=True, db_index=True, help_text='Linked payment transaction (if applicable)', null=True)),
                ('transaction_type', models.CharField(choices=[('DEPOSIT', 'Deposit (Advance Payment)'), ('DUES_DEDUCTION', 'Dues Deduction'), ('REFUND', 'Refund'), ('ADJUSTMENT', 'Manual Adjustment')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Positive for deposits, negative for deductions', max_digits=12)),
                ('balance_after', models.DecimalField(decimal_places=2, help_text='Credit balance after this transaction', max_digits=12)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('created_by_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Credit Transaction',
                'verbose_name_plural': 'Credit Transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DiscountConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('org_id', models.UUIDField(db_index=True)),
                ('name', models.CharField(help_text="e.g., 'Early Payment Discount', '12-Month Advance Discount'", max_length=100)),
                ('description', models.TextField(blank=True)),
                ('discount_type', models.CharField(choices=[('PERCENTAGE', 'Percentage'), ('FLAT', 'Flat Amount')], max_length=10)),
                ('value', models.DecimalField(decimal_places=2, help_text='Percentage (e.g., 20.00 for 20%) or flat amount', max_digits=10)),
                ('applicable_categories', models.JSONField(blank=True, default=list, help_text='List of category IDs this discount applies to (empty = all)')),
                ('min_months', models.PositiveSmallIntegerField(default=1, help_text='Minimum months for bulk payment discount (e.g., 12 for yearly)')),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Discount Configuration',
                'verbose_name_plural': 'Discount Configurations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PenaltyConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('org_id', models.UUIDField(db_index=True)),
                ('monthly_due_rate', models.DecimalField(decimal_places=2, help_text='Monthly dues amount (flat) or rate per sqm', max_digits=10)),
                ('due_day', models.PositiveSmallIntegerField(default=5, help_text='Day of month dues are due')),
                ('grace_period_days', models.PositiveSmallIntegerField(default=15)),
                ('late_penalty_type', models.CharField(choices=[('FLAT', 'Flat Fee'), ('PERCENT', 'Percentage')], default='PERCENT', max_length=20)),
                ('late_penalty_rate', models.DecimalField(decimal_places=2, default=Decimal('2.00'), help_text='Penalty rate (e.g., 2.00 for 2%)', max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Penalty Configuration (Legacy)',
                'verbose_name_plural': 'Penalty Configurations (Legacy)',
            },
        ),
        migrations.CreateModel(
            name='PenaltyPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('org_id', models.UUIDField(db_index=True)),
                ('name', models.CharField(help_text="e.g., 'Late Payment Penalty'", max_length=100)),
                ('description', models.TextField(blank=True)),
                ('rate_type', models.CharField(choices=[('FLAT', 'Flat Fee'), ('PERCENT', 'Percentage')], default='PERCENT', max_length=10)),
                ('rate_value', models.DecimalField(decimal_places=2, help_text='Rate value (e.g., 2.00 for 2% or flat amount)', max_digits=5)),
                ('grace_period_days', models.PositiveSmallIntegerField(default=15, help_text='Days after due date before penalty applies')),
                ('applicable_categories', models.JSONField(blank=True, default=list, help_text='List of category IDs this penalty applies to (empty = all)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Penalty Policy',
                'verbose_name_plural': 'Penalty Policies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('org_id', models.UUIDField(db_index=True)),
                ('unit_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('asset_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('category_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('transaction_type', models.CharField(choices=[('INCOME', 'Income'), ('EXPENSE', 'Expense')], max_length=10)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('payment_type', models.CharField(choices=[('EXACT', 'Exact Payment'), ('ADVANCE', 'Advance Payment')], default='EXACT', help_text='EXACT requires amount to match dues; ADVANCE allows overpayment to credit', max_length=10)),
                ('gross_amount', models.DecimalField(decimal_places=2, help_text='Amount before adjustments', max_digits=12)),
                ('net_amount', models.DecimalField(decimal_places=2, help_text='Final amount after discounts/penalties', max_digits=12)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('category', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('payer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('reference_number', models.CharField(blank=True, help_text='External reference (OR number, check number, etc.)', max_length=100, null=True)),
                ('receipt_image', models.URLField(blank=True, null=True)),
                ('requires_receipt', models.BooleanField(default=False)),
                ('receipt_verified', models.BooleanField(default=False)),
                ('transaction_date', models.DateField()),
                ('created_by_id', models.UUIDField(blank=True, null=True)),
                ('approved_by_id', models.UUIDField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-transaction_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TransactionAdjustment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_id', models.UUIDField(db_index=True)),
                ('adjustment_type', models.CharField(choices=[('DISCOUNT', 'Discount'), ('PENALTY', 'Penalty')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Positive for discounts/penalties (applied to gross)', max_digits=12)),
                ('reason', models.CharField(max_length=255)),
                ('penalty_months', models.PositiveSmallIntegerField(blank=True, help_text='Number of months overdue (for penalty calculation)', null=True)),
                ('penalty_rate', models.DecimalField(blank=True, decimal_places=4, help_text='Interest rate used (e.g., 0.02 for 2%)', max_digits=5, null=True)),
                ('created_by_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Transaction Adjustment',
                'verbose_name_plural': 'Transaction Adjustments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TransactionAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_id', models.UUIDField(db_index=True)),
                ('file_url', models.URLField(help_text='URL to the uploaded file (S3 or local)')),
                ('file_name', models.CharField(max_length=255)),
                ('file_type', models.CharField(help_text='MIME type (image/jpeg, image/png, application/pdf)', max_length=50)),
                ('file_size', models.PositiveIntegerField(help_text='File size in bytes')),
                ('uploaded_by_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Transaction Attachment',
                'verbose_name_plural': 'Transaction Attachments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UnitCredit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('org_id', models.UUIDField(db_index=True)),
                ('unit_id', models.UUIDField(db_index=True, unique=True)),
                ('credit_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Current available credit from advance payments', max_digits=12)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Unit Credit',
                'verbose_name_plural': 'Unit Credits',
            },
        ),
        migrations.CreateModel(
            name='DuesStatement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('org_id', models.UUIDField(db_index=True)),
                ('unit_id', models.UUIDField(db_index=True)),
                ('statement_month', models.PositiveSmallIntegerField(help_text='Month (1-12)')),
                ('statement_year', models.PositiveSmallIntegerField(help_text='Year')),
                ('base_amount', models.DecimalField(decimal_places=2, help_text='Original dues amount', max_digits=12)),
                ('penalty_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total penalties applied', max_digits=12)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total discounts applied', max_digits=12)),
                ('net_amount', models.DecimalField(decimal_places=2, help_text='Final amount due (base + penalty - discount)', max_digits=12)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount already paid', max_digits=12)),
                ('status', models.CharField(choices=[('UNPAID', 'Unpaid'), ('PARTIAL', 'Partially Paid'), ('PAID', 'Paid'), ('OVERDUE', 'Overdue'), ('WAIVED', 'Waived')], default='UNPAID', max_length=20)),
                ('due_date', models.DateField()),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('payment_transaction_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Dues Statement',
                'verbose_name_plural': 'Dues Statements',
                'ordering': ['-statement_year', '-statement_month'],
                'unique_together': {('org_id', 'unit_id', 'statement_year', 'statement_month')},
            },
        ),
        migrations.CreateModel(
            name='TransactionCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('org_id', models.UUIDField(db_index=True)),
                ('name', models.CharField(max_length=100)),
                ('transaction_type', models.CharField(choices=[('INCOME', 'Income'), ('EXPENSE', 'Expense')], max_length=10)),
                ('description', models.TextField(blank=True)),
                ('is_default', models.BooleanField(default=False, help_text='System-generated default category')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Transaction Category',
                'verbose_name_plural': 'Transaction Categories',
                'ordering': ['name'],
                'unique_together': {('org_id', 'name', 'transaction_type')},
            },
        ),
    ]
