# Generated by Django 6.0.1 on 2026-01-14 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0001_financial_ledger_models'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='approved_at',
            new_name='verified_at',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='approved_by_id',
            new_name='verified_by_id',
        ),
        migrations.AddField(
            model_name='transaction',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Checked and verified by board/admin'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending Verification'), ('POSTED', 'Posted'), ('CANCELLED', 'Cancelled')], default='POSTED', max_length=20),
        ),
    ]
