# Generated by Django 6.0.1 on 2026-01-14 09:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0002_rename_approved_at_transaction_verified_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('org_id', models.UUIDField(db_index=True, unique=True)),
                ('monthly_dues_amount', models.DecimalField(decimal_places=2, help_text='Base monthly dues amount per unit', max_digits=12)),
                ('billing_day', models.PositiveSmallIntegerField(default=1, help_text='Day of month to generate statements (1-28)')),
                ('grace_period_days', models.PositiveSmallIntegerField(default=15, help_text='Days after due date before penalties apply')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Billing Configuration',
                'verbose_name_plural': 'Billing Configurations',
            },
        ),
        migrations.DeleteModel(
            name='PenaltyConfig',
        ),
    ]
