# Generated by Django 6.0.1 on 2026-01-23 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0003_billingconfig_delete_penaltyconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='disbursement_date',
            field=models.DateField(blank=True, help_text='Date when payment was actually made (if different from transaction date)', null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='is_disbursed',
            field=models.BooleanField(default=True, help_text='True if cash has left the organization. False means Account Payable.'),
        ),
    ]
