# Generated by Django 5.2.10 on 2026-02-09 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0004_transaction_disbursement_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Cash'), ('BANK_TRANSFER', 'Bank Transfer'), ('GCASH', 'GCash'), ('CHECK', 'Check'), ('OTHER', 'Other')], default='CASH', help_text='Method of payment', max_length=20),
        ),
    ]
