# Generated by Django 6.0.1 on 2026-01-15 13:10

import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('org_id', models.UUIDField(db_index=True)),
                ('name', models.CharField(max_length=255)),
                ('asset_type', models.CharField(choices=[('REVENUE', 'Revenue-Generating'), ('SHARED', 'Shared Infrastructure')], default='SHARED', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('rental_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Rental rate per hour (for revenue facilities)', max_digits=10, null=True)),
                ('capacity', models.PositiveIntegerField(blank=True, help_text='Maximum capacity (number of people)', null=True)),
                ('location', models.CharField(blank=True, help_text='Physical location within the subdivision/building', max_length=255)),
                ('requires_deposit', models.BooleanField(default=False)),
                ('deposit_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Security deposit amount', max_digits=10, null=True)),
                ('min_duration_hours', models.PositiveIntegerField(default=1, help_text='Minimum reservation duration in hours')),
                ('max_duration_hours', models.PositiveIntegerField(default=24, help_text='Maximum reservation duration in hours')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ReservationConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('org_id', models.UUIDField(db_index=True, unique=True)),
                ('expiration_hours', models.PositiveIntegerField(default=48, help_text='Hours until unpaid homeowner reservation expires (0 = no expiration)')),
                ('allow_same_day_booking', models.BooleanField(default=True, help_text='Allow reservations for today')),
                ('min_advance_hours', models.PositiveIntegerField(default=0, help_text='Minimum hours in advance to book (0 = no limit)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Reservation Configuration',
                'verbose_name_plural': 'Reservation Configurations',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('org_id', models.UUIDField(db_index=True)),
                ('asset_id', models.UUIDField(db_index=True)),
                ('unit_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('reserved_by_id', models.UUIDField(db_index=True)),
                ('reserved_by_name', models.CharField(max_length=255)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('purpose', models.TextField(blank=True)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hours', models.PositiveIntegerField()),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('deposit_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('status', models.CharField(choices=[('PENDING_PAYMENT', 'Pending Payment'), ('CONFIRMED', 'Confirmed'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired')], default='PENDING_PAYMENT', max_length=20)),
                ('payment_status', models.CharField(choices=[('UNPAID', 'Unpaid'), ('PARTIAL', 'Partially Paid'), ('PAID', 'Paid'), ('REFUNDED', 'Refunded')], default='UNPAID', max_length=20)),
                ('income_transaction_id', models.UUIDField(blank=True, null=True)),
                ('applied_discount_ids', models.JSONField(blank=True, default=list)),
                ('approved_by_id', models.UUIDField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_by_id', models.UUIDField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='When unpaid reservation expires (null for staff/board reservations)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-start_datetime'],
                'indexes': [models.Index(fields=['org_id', 'asset_id', 'status'], name='assets_rese_org_id_e7a327_idx'), models.Index(fields=['org_id', 'reserved_by_id'], name='assets_rese_org_id_ab9183_idx'), models.Index(fields=['expires_at'], name='assets_rese_expires_4ef3ef_idx')],
            },
        ),
    ]
