# Generated by Django 5.2.10 on 2026-02-03 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_alter_reservation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='image_url',
            field=models.URLField(blank=True, help_text='URL to asset image (e.g., S3 bucket URL)', max_length=500, null=True),
        ),
    ]
