# Generated by Django 5.2.10 on 2026-02-09 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_add_image_url_to_asset'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationconfig',
            name='operating_hours_end',
            field=models.TimeField(default='22:00', help_text='End of operating hours (e.g., 22:00)'),
        ),
        migrations.AddField(
            model_name='reservationconfig',
            name='operating_hours_start',
            field=models.TimeField(default='09:00', help_text='Start of operating hours (e.g., 09:00)'),
        ),
    ]
