# Generated by Django 6.0.1 on 2026-01-12 10:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('org_type', models.CharField(choices=[('SUBDIVISION', 'Subdivision'), ('CONDOMINIUM', 'Condominium')], default='SUBDIVISION', max_length=20)),
                ('settings', models.JSONField(default=dict, help_text='Flexible metadata (e.g., label overrides for Condo vs Subdivision)')),
                ('logo', models.URLField(blank=True, null=True)),
                ('tin', models.CharField(blank=True, max_length=50, null=True, verbose_name='TIN')),
                ('dhsud_registration', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('fiscal_year_start_month', models.PositiveSmallIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
